language: android
android:
  components:
    - tools
    - platform-tools

    # The SDK version used to compile this project
    - android-28

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - openjdk8
before_install:
  - yes | sdkmanager "build-tools;29.0.2"
  - yes | sdkmanager "platforms;android-28"
  - git clone https://github.com/okta/okta-idx-java.git
  - cd okta-idx-java
  - mvn install
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - "./gradlew clean build test"
