version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2021.10.2
    steps:
      - run:
          name: Build
          command: ./gradlew build assembleAndroidTest testDebugUnitTest --parallel

workflows:
  build_and_test:
    jobs:
      - build
