version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.04.1
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew assembleDebug testDebugUnitTest assembleAndroidTest

workflows:
  build_and_test:
    jobs:
      - build
