version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2021.10.2
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build assembleAndroidTest testDebugUnitTest

workflows:
  build_and_test:
    jobs:
      - build
