version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

jobs:
  build:
    resource_class: large
    docker:
      - image: cimg/openjdk:18.0
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew assembleDebug testDebugUnitTest assembleAndroidTest

  lint:
    docker:
      - image: cimg/openjdk:18.0
    steps:
      - checkout
      - run:
          name: Lint
          command: ./gradlew spotlessCheck apiCheck

workflows:
  build_and_test:
    jobs:
      - build
      - lint
