version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0
  android: circleci/android@2.1.2

jobs:
  build:
    resource_class: large
    docker:
      - image: cimg/android:2022.06.1
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Build
                command: ./gradlew assembleDebug testDebugUnitTest assembleAndroidTest

  lint:
    docker:
      - image: cimg/openjdk:18.0.1
    steps:
      - checkout
      - android/accept-licenses
      - run:
          name: Lint
          command: ./gradlew spotlessCheck apiCheck

workflows:
  build_and_test:
    jobs:
      - build
      - lint
